# Generated by Django 3.0.8 on 2021-04-03 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discuss', '0005_auto_20210403_1544'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discussion',
            options={'verbose_name': 'Discussion', 'verbose_name_plural': 'Discussions'},
        ),
    ]
