# Generated by Django 3.0.8 on 2021-04-10 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discuss', '0009_topic'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topic',
            options={'verbose_name': 'Topic', 'verbose_name_plural': 'Topics'},
        ),
    ]
