# Generated by Django 3.0.8 on 2021-04-10 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discuss', '0010_auto_20210410_2016'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussion',
            name='discussion_topic',
            field=models.CharField(default=False, max_length=60),
        ),
    ]
