# Generated by Django 3.0.8 on 2021-04-10 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discuss', '0011_discussion_discussion_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discussion',
            name='discussion_topic',
            field=models.CharField(default='', max_length=60),
        ),
    ]
