# Generated by Django 3.0.8 on 2021-04-15 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discuss', '0012_auto_20210410_2019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discussion',
            name='discussion_topic',
        ),
        migrations.AddField(
            model_name='discussion',
            name='discussion_topic',
            field=models.ManyToManyField(to='discuss.Topic'),
        ),
    ]
