# Generated by Django 3.0.8 on 2021-04-15 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('discuss', '0013_auto_20210415_2225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discussion',
            name='discussion_topic',
        ),
        migrations.AddField(
            model_name='discussion',
            name='discussion_topic',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='discuss.Topic'),
        ),
    ]
