# Generated by Django 3.0.8 on 2021-04-15 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discuss', '0016_auto_20210415_2258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discussion',
            name='content',
            field=models.TextField(max_length=2000),
        ),
    ]
