# Generated by Django 3.0.8 on 2021-05-11 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discuss', '0017_auto_20210415_2300'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussion',
            name='discussion_picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
