# Generated by Django 3.0.8 on 2021-05-11 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discuss', '0018_discussion_discussion_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discussion',
            name='creation_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
